### PR TITLE
02_01/Susanna

### PR DESCRIPTION
**Pull request by SusieC5**
Here's answers for 5, 7, 13, 25

### CODE REVIEW

**Review by comorekf — CHANGES_REQUESTED** [review]
The formatting and the answers look great. Can you just add the code-block markup around the actual comands to highlight them?
for example `command parameter`

**Comment by SusieC5** [comment]
Commands should stand out more now :)

**Review by comorekf — APPROVED** [review]
all good

**Comment by SusieC5** [comment]
Changes for Q4 2023 completed.

**Pull request merged**
